spring:
  application:
    name: learning
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  output:
    ansi:
      enabled: ALWAYS

  logging:
    level:
      org:
        springframework:
          web: DEBUG
    pattern:
      console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr([%thread]){magenta} %clr(%-5level) %clr(%logger{36}){cyan} %clr(-){faint} %msg%n"